#!/bin/python3

print("content-type: text/json")
print()


import subprocess as sp
import cgi 
import json
import datetime


query = cgi.FieldStorage()

fileitem = query['DockerFile']


file_content = fileitem.file.read().decode()


img_name = query.getvalue("img_name")



tag = query.getvalue("img_tag")


content = str(query.getvalue("data-content"))

result=""

#print(content)

#print(file_content)

sp.getstatusoutput('sudo touch Dockerfile')[1]

sp.getstatusoutput('sudo chmod o+rwx Dockerfile')[1]

if tag == '':
	tag = 'latest'

if content != '':
	file_content = content
	

create_status,create_output = sp.getstatusoutput(f'sudo echo "{file_content}" > Dockerfile')



#if create_status == 0:

status,output = sp.getstatusoutput(f'sudo docker build  -t {img_name}:{tag} .')


if status == 0:

    result = json.dumps({
                    "image" : str(img_name)+ ":" + str(tag),
                    "status": "build successfully",
                    'created_at': str(datetime.datetime.now())
                        },indent = 4)
else:

    result = json.dumps({
                    "image" : str(img_name)+ ":" + str(tag),
                    "status": "build failed",
                    'tried_at': str(datetime.datetime.now()),
                    "reason" : str(output)
                    },indent= 4)


print(result)

#print(create_output)






