#!/bin/python3

print("content-type: text/json")
print()

import subprocess as sp
import cgi 
import json
import datetime

query = cgi.FieldStorage()


con_name = query.getvalue("con_name")

to_stop = query.getvalue("to_stop")

result=""


status,output = sp.getstatusoutput(f'sudo docker stop  {con_name}')

if to_stop == "on":
	sp.getstatusoutput(f'sudo docker rm -f {con_name}')

if status == 0:
    result =json.dumps({
             "name" : str(con_name),
             "status": "stopped",
            'stopped_at': str(datetime.datetime.now())
             },indent=4)
else:
    result =json.dumps({
    "name" : str(con_name),
    "status": "error occured",
    'tried_at': str(datetime.datetime.now()),
    "reason" : str(output)
            },indent=4)

print(result)

    






